<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE TOOL>
<TOOL
TIPDIAM='76'
SYRDIAM='587'
PATHWIDTH='55'
PATHHEIGHT='875'
JOGSPEED='5'
SUCKBACK='85'
PUSHOUT='76'
PATHSPEED='5'
PAUSEPATHS='8'
CLEARANCE='5'
DEPOSITIONRATE='55'
>
</TOOL>