# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/fabqtDialog.ui'
#
# Created: Mon Aug 16 11:53:00 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 716)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setWindowTitle("FabQt")
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qvtkWidget = QVTKRenderWindowInteractor(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.qvtkWidget.sizePolicy().hasHeightForWidth())
        self.qvtkWidget.setSizePolicy(sizePolicy)
        self.qvtkWidget.setObjectName("qvtkWidget")
        self.verticalLayout_2.addWidget(self.qvtkWidget)
        self.logTextBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.logTextBrowser.setMinimumSize(QtCore.QSize(300, 80))
        self.logTextBrowser.setMaximumSize(QtCore.QSize(16777215, 80))
        self.logTextBrowser.setAcceptDrops(False)
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.verticalLayout_2.addWidget(self.logTextBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 23))
        self.menubar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.menubar.setAcceptDrops(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuShow_Tools = QtGui.QMenu(self.menubar)
        self.menuShow_Tools.setObjectName("menuShow_Tools")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuLanguage = QtGui.QMenu(self.menubar)
        self.menuLanguage.setObjectName("menuLanguage")
        MainWindow.setMenuBar(self.menubar)
        self.mainDock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainDock.sizePolicy().hasHeightForWidth())
        self.mainDock.setSizePolicy(sizePolicy)
        self.mainDock.setMinimumSize(QtCore.QSize(270, 636))
        self.mainDock.setMaximumSize(QtCore.QSize(270, 524287))
        self.mainDock.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.mainDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.mainDock.setObjectName("mainDock")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainTabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabWidget.sizePolicy().hasHeightForWidth())
        self.mainTabWidget.setSizePolicy(sizePolicy)
        self.mainTabWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.mainTabWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.moveTab = QtGui.QWidget()
        self.moveTab.setObjectName("moveTab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.moveTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.incrementLabel = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.incrementLabel.setFont(font)
        self.incrementLabel.setObjectName("incrementLabel")
        self.gridLayout.addWidget(self.incrementLabel, 0, 1, 1, 1)
        self.positionLabel = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.positionLabel.setFont(font)
        self.positionLabel.setObjectName("positionLabel")
        self.gridLayout.addWidget(self.positionLabel, 0, 2, 1, 1)
        self.commandLabel = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.commandLabel.setFont(font)
        self.commandLabel.setObjectName("commandLabel")
        self.gridLayout.addWidget(self.commandLabel, 0, 3, 1, 1)
        self.x_Label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.x_Label.setFont(font)
        self.x_Label.setText("X")
        self.x_Label.setObjectName("x_Label")
        self.gridLayout.addWidget(self.x_Label, 1, 0, 1, 1)
        self.x_PositionLineEdit = QtGui.QLineEdit(self.moveTab)
        self.x_PositionLineEdit.setEnabled(False)
        self.x_PositionLineEdit.setMinimumSize(QtCore.QSize(60, 27))
        self.x_PositionLineEdit.setMaximumSize(QtCore.QSize(60, 27))
        self.x_PositionLineEdit.setAcceptDrops(False)
        self.x_PositionLineEdit.setInputMask("999.99; ")
        self.x_PositionLineEdit.setText("000.00")
        self.x_PositionLineEdit.setMaxLength(6)
        self.x_PositionLineEdit.setFrame(True)
        self.x_PositionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.x_PositionLineEdit.setObjectName("x_PositionLineEdit")
        self.gridLayout.addWidget(self.x_PositionLineEdit, 1, 2, 1, 1)
        self.x_Commanded = QtGui.QDoubleSpinBox(self.moveTab)
        self.x_Commanded.setMinimumSize(QtCore.QSize(80, 0))
        self.x_Commanded.setMaximumSize(QtCore.QSize(80, 16777215))
        self.x_Commanded.setAlignment(QtCore.Qt.AlignCenter)
        self.x_Commanded.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.x_Commanded.setMinimum(-300.0)
        self.x_Commanded.setMaximum(300.0)
        self.x_Commanded.setObjectName("x_Commanded")
        self.gridLayout.addWidget(self.x_Commanded, 1, 3, 1, 1)
        self.y_Label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.y_Label.setFont(font)
        self.y_Label.setText("Y")
        self.y_Label.setObjectName("y_Label")
        self.gridLayout.addWidget(self.y_Label, 2, 0, 1, 1)
        self.y_IncrementLineEdit = QtGui.QLineEdit(self.moveTab)
        self.y_IncrementLineEdit.setMinimumSize(QtCore.QSize(40, 27))
        self.y_IncrementLineEdit.setMaximumSize(QtCore.QSize(40, 27))
        self.y_IncrementLineEdit.setAcceptDrops(False)
        self.y_IncrementLineEdit.setInputMask("9.99; ")
        self.y_IncrementLineEdit.setText("1.00")
        self.y_IncrementLineEdit.setMaxLength(4)
        self.y_IncrementLineEdit.setFrame(True)
        self.y_IncrementLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.y_IncrementLineEdit.setObjectName("y_IncrementLineEdit")
        self.gridLayout.addWidget(self.y_IncrementLineEdit, 2, 1, 1, 1)
        self.y_PositionLineEdit = QtGui.QLineEdit(self.moveTab)
        self.y_PositionLineEdit.setEnabled(False)
        self.y_PositionLineEdit.setMinimumSize(QtCore.QSize(60, 27))
        self.y_PositionLineEdit.setMaximumSize(QtCore.QSize(60, 27))
        self.y_PositionLineEdit.setAcceptDrops(False)
        self.y_PositionLineEdit.setInputMask("999.99; ")
        self.y_PositionLineEdit.setText("000.00")
        self.y_PositionLineEdit.setMaxLength(6)
        self.y_PositionLineEdit.setFrame(True)
        self.y_PositionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.y_PositionLineEdit.setObjectName("y_PositionLineEdit")
        self.gridLayout.addWidget(self.y_PositionLineEdit, 2, 2, 1, 1)
        self.y_Commanded = QtGui.QDoubleSpinBox(self.moveTab)
        self.y_Commanded.setMinimumSize(QtCore.QSize(80, 0))
        self.y_Commanded.setMaximumSize(QtCore.QSize(80, 16777215))
        self.y_Commanded.setAlignment(QtCore.Qt.AlignCenter)
        self.y_Commanded.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.y_Commanded.setMinimum(-300.0)
        self.y_Commanded.setMaximum(300.0)
        self.y_Commanded.setObjectName("y_Commanded")
        self.gridLayout.addWidget(self.y_Commanded, 2, 3, 1, 1)
        self.z_Label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.z_Label.setFont(font)
        self.z_Label.setText("Z")
        self.z_Label.setObjectName("z_Label")
        self.gridLayout.addWidget(self.z_Label, 3, 0, 1, 1)
        self.z_IncrementLineEdit = QtGui.QLineEdit(self.moveTab)
        self.z_IncrementLineEdit.setMinimumSize(QtCore.QSize(40, 27))
        self.z_IncrementLineEdit.setMaximumSize(QtCore.QSize(40, 27))
        self.z_IncrementLineEdit.setAcceptDrops(False)
        self.z_IncrementLineEdit.setInputMask("9.99; ")
        self.z_IncrementLineEdit.setText("1.00")
        self.z_IncrementLineEdit.setMaxLength(4)
        self.z_IncrementLineEdit.setFrame(True)
        self.z_IncrementLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.z_IncrementLineEdit.setObjectName("z_IncrementLineEdit")
        self.gridLayout.addWidget(self.z_IncrementLineEdit, 3, 1, 1, 1)
        self.z_PositionLineEdit = QtGui.QLineEdit(self.moveTab)
        self.z_PositionLineEdit.setEnabled(False)
        self.z_PositionLineEdit.setMinimumSize(QtCore.QSize(60, 27))
        self.z_PositionLineEdit.setMaximumSize(QtCore.QSize(60, 27))
        self.z_PositionLineEdit.setAcceptDrops(False)
        self.z_PositionLineEdit.setInputMask("999.99; ")
        self.z_PositionLineEdit.setText("000.00")
        self.z_PositionLineEdit.setMaxLength(6)
        self.z_PositionLineEdit.setFrame(True)
        self.z_PositionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.z_PositionLineEdit.setObjectName("z_PositionLineEdit")
        self.gridLayout.addWidget(self.z_PositionLineEdit, 3, 2, 1, 1)
        self.z_Commanded = QtGui.QDoubleSpinBox(self.moveTab)
        self.z_Commanded.setMinimumSize(QtCore.QSize(80, 0))
        self.z_Commanded.setMaximumSize(QtCore.QSize(80, 16777215))
        self.z_Commanded.setAlignment(QtCore.Qt.AlignCenter)
        self.z_Commanded.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.z_Commanded.setMinimum(-300.0)
        self.z_Commanded.setMaximum(300.0)
        self.z_Commanded.setObjectName("z_Commanded")
        self.gridLayout.addWidget(self.z_Commanded, 3, 3, 1, 1)
        self.u_Label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.u_Label.setFont(font)
        self.u_Label.setText("U")
        self.u_Label.setObjectName("u_Label")
        self.gridLayout.addWidget(self.u_Label, 5, 0, 1, 1)
        self.u_IncrementLineEdit = QtGui.QLineEdit(self.moveTab)
        self.u_IncrementLineEdit.setMinimumSize(QtCore.QSize(40, 27))
        self.u_IncrementLineEdit.setMaximumSize(QtCore.QSize(40, 27))
        self.u_IncrementLineEdit.setAcceptDrops(False)
        self.u_IncrementLineEdit.setInputMask("9.99; ")
        self.u_IncrementLineEdit.setText("0.10")
        self.u_IncrementLineEdit.setMaxLength(4)
        self.u_IncrementLineEdit.setFrame(True)
        self.u_IncrementLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.u_IncrementLineEdit.setObjectName("u_IncrementLineEdit")
        self.gridLayout.addWidget(self.u_IncrementLineEdit, 5, 1, 1, 1)
        self.u_PositionLineEdit = QtGui.QLineEdit(self.moveTab)
        self.u_PositionLineEdit.setEnabled(False)
        self.u_PositionLineEdit.setMinimumSize(QtCore.QSize(60, 27))
        self.u_PositionLineEdit.setMaximumSize(QtCore.QSize(60, 27))
        self.u_PositionLineEdit.setAcceptDrops(False)
        self.u_PositionLineEdit.setInputMask("999.99; ")
        self.u_PositionLineEdit.setText("000.00")
        self.u_PositionLineEdit.setMaxLength(6)
        self.u_PositionLineEdit.setFrame(True)
        self.u_PositionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.u_PositionLineEdit.setObjectName("u_PositionLineEdit")
        self.gridLayout.addWidget(self.u_PositionLineEdit, 5, 2, 1, 1)
        self.u_Commanded = QtGui.QDoubleSpinBox(self.moveTab)
        self.u_Commanded.setMinimumSize(QtCore.QSize(80, 0))
        self.u_Commanded.setMaximumSize(QtCore.QSize(80, 16777215))
        self.u_Commanded.setAlignment(QtCore.Qt.AlignCenter)
        self.u_Commanded.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.u_Commanded.setMinimum(-300.0)
        self.u_Commanded.setMaximum(300.0)
        self.u_Commanded.setSingleStep(0.1)
        self.u_Commanded.setObjectName("u_Commanded")
        self.gridLayout.addWidget(self.u_Commanded, 5, 3, 1, 1)
        self.v_Label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.v_Label.setFont(font)
        self.v_Label.setText("V")
        self.v_Label.setObjectName("v_Label")
        self.gridLayout.addWidget(self.v_Label, 6, 0, 1, 1)
        self.v_IncrementLineEdit = QtGui.QLineEdit(self.moveTab)
        self.v_IncrementLineEdit.setMinimumSize(QtCore.QSize(40, 27))
        self.v_IncrementLineEdit.setMaximumSize(QtCore.QSize(40, 27))
        self.v_IncrementLineEdit.setAcceptDrops(False)
        self.v_IncrementLineEdit.setInputMask("9.99; ")
        self.v_IncrementLineEdit.setText("0.10")
        self.v_IncrementLineEdit.setMaxLength(4)
        self.v_IncrementLineEdit.setFrame(True)
        self.v_IncrementLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.v_IncrementLineEdit.setObjectName("v_IncrementLineEdit")
        self.gridLayout.addWidget(self.v_IncrementLineEdit, 6, 1, 1, 1)
        self.v_PositionLineEdit = QtGui.QLineEdit(self.moveTab)
        self.v_PositionLineEdit.setEnabled(False)
        self.v_PositionLineEdit.setMinimumSize(QtCore.QSize(60, 27))
        self.v_PositionLineEdit.setMaximumSize(QtCore.QSize(60, 27))
        self.v_PositionLineEdit.setAcceptDrops(False)
        self.v_PositionLineEdit.setInputMask("999.99; ")
        self.v_PositionLineEdit.setText("000.00")
        self.v_PositionLineEdit.setMaxLength(6)
        self.v_PositionLineEdit.setFrame(True)
        self.v_PositionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.v_PositionLineEdit.setObjectName("v_PositionLineEdit")
        self.gridLayout.addWidget(self.v_PositionLineEdit, 6, 2, 1, 1)
        self.v_Commanded = QtGui.QDoubleSpinBox(self.moveTab)
        self.v_Commanded.setMinimumSize(QtCore.QSize(80, 0))
        self.v_Commanded.setMaximumSize(QtCore.QSize(80, 16777215))
        self.v_Commanded.setAlignment(QtCore.Qt.AlignCenter)
        self.v_Commanded.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.v_Commanded.setMinimum(-300.0)
        self.v_Commanded.setMaximum(300.0)
        self.v_Commanded.setSingleStep(0.1)
        self.v_Commanded.setObjectName("v_Commanded")
        self.gridLayout.addWidget(self.v_Commanded, 6, 3, 1, 1)
        self.line = QtGui.QFrame(self.moveTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 4)
        self.x_IncrementLineEdit = QtGui.QLineEdit(self.moveTab)
        self.x_IncrementLineEdit.setMinimumSize(QtCore.QSize(40, 27))
        self.x_IncrementLineEdit.setMaximumSize(QtCore.QSize(40, 27))
        self.x_IncrementLineEdit.setAcceptDrops(False)
        self.x_IncrementLineEdit.setInputMask("9.99; ")
        self.x_IncrementLineEdit.setText("1.00")
        self.x_IncrementLineEdit.setMaxLength(4)
        self.x_IncrementLineEdit.setFrame(True)
        self.x_IncrementLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.x_IncrementLineEdit.setObjectName("x_IncrementLineEdit")
        self.gridLayout.addWidget(self.x_IncrementLineEdit, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.line_3 = QtGui.QFrame(self.moveTab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.syringe1Label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.syringe1Label.setFont(font)
        self.syringe1Label.setObjectName("syringe1Label")
        self.verticalLayout.addWidget(self.syringe1Label)
        self.syringe1ComboBox = QtGui.QComboBox(self.moveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syringe1ComboBox.sizePolicy().hasHeightForWidth())
        self.syringe1ComboBox.setSizePolicy(sizePolicy)
        self.syringe1ComboBox.setMinimumSize(QtCore.QSize(226, 25))
        self.syringe1ComboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.syringe1ComboBox.setObjectName("syringe1ComboBox")
        self.verticalLayout.addWidget(self.syringe1ComboBox)
        self.syringe2Label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.syringe2Label.setFont(font)
        self.syringe2Label.setObjectName("syringe2Label")
        self.verticalLayout.addWidget(self.syringe2Label)
        self.syringe2ComboBox = QtGui.QComboBox(self.moveTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syringe2ComboBox.sizePolicy().hasHeightForWidth())
        self.syringe2ComboBox.setSizePolicy(sizePolicy)
        self.syringe2ComboBox.setMinimumSize(QtCore.QSize(226, 25))
        self.syringe2ComboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.syringe2ComboBox.setObjectName("syringe2ComboBox")
        self.verticalLayout.addWidget(self.syringe2ComboBox)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.line_4 = QtGui.QFrame(self.moveTab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.autoCalibrateButton = QtGui.QPushButton(self.moveTab)
        self.autoCalibrateButton.setObjectName("autoCalibrateButton")
        self.gridLayout_4.addWidget(self.autoCalibrateButton, 0, 0, 1, 3)
        self.setHomeButton = QtGui.QPushButton(self.moveTab)
        self.setHomeButton.setMinimumSize(QtCore.QSize(70, 0))
        self.setHomeButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setHomeButton.setObjectName("setHomeButton")
        self.gridLayout_4.addWidget(self.setHomeButton, 1, 0, 1, 1)
        self.setSafeButton = QtGui.QPushButton(self.moveTab)
        self.setSafeButton.setMinimumSize(QtCore.QSize(70, 0))
        self.setSafeButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setSafeButton.setObjectName("setSafeButton")
        self.gridLayout_4.addWidget(self.setSafeButton, 1, 1, 1, 1)
        self.setOriginButton = QtGui.QPushButton(self.moveTab)
        self.setOriginButton.setMinimumSize(QtCore.QSize(70, 0))
        self.setOriginButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setOriginButton.setObjectName("setOriginButton")
        self.gridLayout_4.addWidget(self.setOriginButton, 1, 2, 1, 1)
        self.goHomeButton = QtGui.QPushButton(self.moveTab)
        self.goHomeButton.setMinimumSize(QtCore.QSize(70, 0))
        self.goHomeButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.goHomeButton.setObjectName("goHomeButton")
        self.gridLayout_4.addWidget(self.goHomeButton, 2, 0, 1, 1)
        self.goSafeButton = QtGui.QPushButton(self.moveTab)
        self.goSafeButton.setMinimumSize(QtCore.QSize(70, 0))
        self.goSafeButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.goSafeButton.setObjectName("goSafeButton")
        self.gridLayout_4.addWidget(self.goSafeButton, 2, 1, 1, 1)
        self.goOriginButton = QtGui.QPushButton(self.moveTab)
        self.goOriginButton.setMinimumSize(QtCore.QSize(70, 0))
        self.goOriginButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.goOriginButton.setObjectName("goOriginButton")
        self.gridLayout_4.addWidget(self.goOriginButton, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.line_7 = QtGui.QFrame(self.moveTab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_5.addWidget(self.line_7)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.NW_Button = QtGui.QPushButton(self.moveTab)
        self.NW_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.NW_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.NW_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/NW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NW_Button.setIcon(icon)
        self.NW_Button.setIconSize(QtCore.QSize(25, 25))
        self.NW_Button.setShortcut("7")
        self.NW_Button.setObjectName("NW_Button")
        self.gridLayout_3.addWidget(self.NW_Button, 0, 0, 1, 1)
        self.N_Button = QtGui.QPushButton(self.moveTab)
        self.N_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.N_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.N_Button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.N_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/N.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.N_Button.setIcon(icon1)
        self.N_Button.setIconSize(QtCore.QSize(25, 25))
        self.N_Button.setShortcut("8")
        self.N_Button.setObjectName("N_Button")
        self.gridLayout_3.addWidget(self.N_Button, 0, 1, 1, 1)
        self.NE_Button = QtGui.QPushButton(self.moveTab)
        self.NE_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.NE_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.NE_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/NE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NE_Button.setIcon(icon2)
        self.NE_Button.setIconSize(QtCore.QSize(25, 25))
        self.NE_Button.setShortcut("9")
        self.NE_Button.setObjectName("NE_Button")
        self.gridLayout_3.addWidget(self.NE_Button, 0, 2, 1, 1)
        self.ZN_Button = QtGui.QPushButton(self.moveTab)
        self.ZN_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.ZN_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.ZN_Button.setText("")
        self.ZN_Button.setIcon(icon1)
        self.ZN_Button.setIconSize(QtCore.QSize(25, 25))
        self.ZN_Button.setShortcut("-")
        self.ZN_Button.setObjectName("ZN_Button")
        self.gridLayout_3.addWidget(self.ZN_Button, 0, 3, 1, 1)
        self.T1N_Button = QtGui.QPushButton(self.moveTab)
        self.T1N_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.T1N_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.T1N_Button.setText("")
        self.T1N_Button.setIcon(icon1)
        self.T1N_Button.setIconSize(QtCore.QSize(25, 25))
        self.T1N_Button.setShortcut("Home")
        self.T1N_Button.setObjectName("T1N_Button")
        self.gridLayout_3.addWidget(self.T1N_Button, 0, 5, 1, 1)
        self.T2N_Button = QtGui.QPushButton(self.moveTab)
        self.T2N_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.T2N_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.T2N_Button.setText("")
        self.T2N_Button.setIcon(icon1)
        self.T2N_Button.setIconSize(QtCore.QSize(25, 25))
        self.T2N_Button.setShortcut("PgUp")
        self.T2N_Button.setObjectName("T2N_Button")
        self.gridLayout_3.addWidget(self.T2N_Button, 0, 6, 1, 1)
        self.W_Button = QtGui.QPushButton(self.moveTab)
        self.W_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.W_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.W_Button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/W.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.W_Button.setIcon(icon3)
        self.W_Button.setIconSize(QtCore.QSize(25, 25))
        self.W_Button.setShortcut("4")
        self.W_Button.setObjectName("W_Button")
        self.gridLayout_3.addWidget(self.W_Button, 1, 0, 1, 1)
        self.E_Button = QtGui.QPushButton(self.moveTab)
        self.E_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.E_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.E_Button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/E.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.E_Button.setIcon(icon4)
        self.E_Button.setIconSize(QtCore.QSize(25, 25))
        self.E_Button.setShortcut("6")
        self.E_Button.setObjectName("E_Button")
        self.gridLayout_3.addWidget(self.E_Button, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setText("Z")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("S1")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setText("S2")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 6, 1, 1)
        self.SW_Button = QtGui.QPushButton(self.moveTab)
        self.SW_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.SW_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.SW_Button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/SW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SW_Button.setIcon(icon5)
        self.SW_Button.setIconSize(QtCore.QSize(25, 25))
        self.SW_Button.setShortcut("1")
        self.SW_Button.setObjectName("SW_Button")
        self.gridLayout_3.addWidget(self.SW_Button, 2, 0, 1, 1)
        self.S_Button = QtGui.QPushButton(self.moveTab)
        self.S_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.S_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.S_Button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/S.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.S_Button.setIcon(icon6)
        self.S_Button.setIconSize(QtCore.QSize(25, 25))
        self.S_Button.setShortcut("2")
        self.S_Button.setObjectName("S_Button")
        self.gridLayout_3.addWidget(self.S_Button, 2, 1, 1, 1)
        self.SE_Button = QtGui.QPushButton(self.moveTab)
        self.SE_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.SE_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.SE_Button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/SE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SE_Button.setIcon(icon7)
        self.SE_Button.setIconSize(QtCore.QSize(25, 25))
        self.SE_Button.setShortcut("3")
        self.SE_Button.setObjectName("SE_Button")
        self.gridLayout_3.addWidget(self.SE_Button, 2, 2, 1, 1)
        self.ZS_Button = QtGui.QPushButton(self.moveTab)
        self.ZS_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.ZS_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.ZS_Button.setText("")
        self.ZS_Button.setIcon(icon6)
        self.ZS_Button.setIconSize(QtCore.QSize(25, 25))
        self.ZS_Button.setShortcut("+")
        self.ZS_Button.setObjectName("ZS_Button")
        self.gridLayout_3.addWidget(self.ZS_Button, 2, 3, 1, 1)
        self.T1S_Button = QtGui.QPushButton(self.moveTab)
        self.T1S_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.T1S_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.T1S_Button.setText("")
        self.T1S_Button.setIcon(icon6)
        self.T1S_Button.setIconSize(QtCore.QSize(25, 25))
        self.T1S_Button.setShortcut("End")
        self.T1S_Button.setObjectName("T1S_Button")
        self.gridLayout_3.addWidget(self.T1S_Button, 2, 5, 1, 1)
        self.T2S_Button = QtGui.QPushButton(self.moveTab)
        self.T2S_Button.setMinimumSize(QtCore.QSize(30, 30))
        self.T2S_Button.setMaximumSize(QtCore.QSize(30, 30))
        self.T2S_Button.setText("")
        self.T2S_Button.setIcon(icon6)
        self.T2S_Button.setIconSize(QtCore.QSize(25, 25))
        self.T2S_Button.setShortcut("PgDown")
        self.T2S_Button.setObjectName("T2S_Button")
        self.gridLayout_3.addWidget(self.T2S_Button, 2, 6, 1, 1)
        self.line_5 = QtGui.QFrame(self.moveTab)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 0, 4, 3, 1)
        self.label_4 = QtGui.QLabel(self.moveTab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setText("XY")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.mainTabWidget.addTab(self.moveTab, "")
        self.modelTab = QtGui.QWidget()
        self.modelTab.setObjectName("modelTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.modelTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.importModelButton = QtGui.QPushButton(self.modelTab)
        self.importModelButton.setObjectName("importModelButton")
        self.verticalLayout_6.addWidget(self.importModelButton)
        self.modelTreeWidget = QtGui.QTreeWidget(self.modelTab)
        self.modelTreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.modelTreeWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.modelTreeWidget.setMidLineWidth(0)
        self.modelTreeWidget.setHeaderHidden(True)
        self.modelTreeWidget.setObjectName("modelTreeWidget")
        self.modelTreeWidget.header().setSortIndicatorShown(False)
        self.verticalLayout_6.addWidget(self.modelTreeWidget)
        self.mainTabWidget.addTab(self.modelTab, "")
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName("configTab")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.configTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.portLabel = QtGui.QLabel(self.configTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout.addWidget(self.portLabel)
        self.portComboBox = QtGui.QComboBox(self.configTab)
        self.portComboBox.setObjectName("portComboBox")
        self.horizontalLayout.addWidget(self.portComboBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.configTab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_10.addWidget(self.line_2)
        self.configTreeWidget = QtGui.QTreeWidget(self.configTab)
        self.configTreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.configTreeWidget.setMidLineWidth(1)
        self.configTreeWidget.setAllColumnsShowFocus(True)
        self.configTreeWidget.setHeaderHidden(False)
        self.configTreeWidget.setObjectName("configTreeWidget")
        item_0 = QtGui.QTreeWidgetItem(self.configTreeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.configTreeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.configTreeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.configTreeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.configTreeWidget)
        self.verticalLayout_10.addWidget(self.configTreeWidget)
        self.line_6 = QtGui.QFrame(self.configTab)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_10.addWidget(self.line_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.printConfigLabel = QtGui.QLabel(self.configTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.printConfigLabel.setFont(font)
        self.printConfigLabel.setObjectName("printConfigLabel")
        self.verticalLayout_3.addWidget(self.printConfigLabel)
        self.pauseAtToolChangeCheckBox = QtGui.QCheckBox(self.configTab)
        self.pauseAtToolChangeCheckBox.setObjectName("pauseAtToolChangeCheckBox")
        self.verticalLayout_3.addWidget(self.pauseAtToolChangeCheckBox)
        self.autoResumeCheckBox = QtGui.QCheckBox(self.configTab)
        self.autoResumeCheckBox.setObjectName("autoResumeCheckBox")
        self.verticalLayout_3.addWidget(self.autoResumeCheckBox)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.line_9 = QtGui.QFrame(self.configTab)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_10.addWidget(self.line_9)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsConfigLabel = QtGui.QLabel(self.configTab)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.graphicsConfigLabel.setFont(font)
        self.graphicsConfigLabel.setObjectName("graphicsConfigLabel")
        self.gridLayout_2.addWidget(self.graphicsConfigLabel, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.showModelCheckBox = QtGui.QCheckBox(self.configTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showModelCheckBox.sizePolicy().hasHeightForWidth())
        self.showModelCheckBox.setSizePolicy(sizePolicy)
        self.showModelCheckBox.setObjectName("showModelCheckBox")
        self.gridLayout_2.addWidget(self.showModelCheckBox, 1, 0, 1, 1)
        self.showPrinterCheckBox = QtGui.QCheckBox(self.configTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showPrinterCheckBox.sizePolicy().hasHeightForWidth())
        self.showPrinterCheckBox.setSizePolicy(sizePolicy)
        self.showPrinterCheckBox.setObjectName("showPrinterCheckBox")
        self.gridLayout_2.addWidget(self.showPrinterCheckBox, 1, 1, 1, 1)
        self.showPathsCheckBox = QtGui.QCheckBox(self.configTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showPathsCheckBox.sizePolicy().hasHeightForWidth())
        self.showPathsCheckBox.setSizePolicy(sizePolicy)
        self.showPathsCheckBox.setObjectName("showPathsCheckBox")
        self.gridLayout_2.addWidget(self.showPathsCheckBox, 2, 0, 1, 1)
        self.showTracesCheckBox = QtGui.QCheckBox(self.configTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showTracesCheckBox.sizePolicy().hasHeightForWidth())
        self.showTracesCheckBox.setSizePolicy(sizePolicy)
        self.showTracesCheckBox.setObjectName("showTracesCheckBox")
        self.gridLayout_2.addWidget(self.showTracesCheckBox, 2, 1, 1, 1)
        self.renderWireframeCheckBox = QtGui.QCheckBox(self.configTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderWireframeCheckBox.sizePolicy().hasHeightForWidth())
        self.renderWireframeCheckBox.setSizePolicy(sizePolicy)
        self.renderWireframeCheckBox.setObjectName("renderWireframeCheckBox")
        self.gridLayout_2.addWidget(self.renderWireframeCheckBox, 3, 0, 1, 2)
        self.resetViewButton = QtGui.QPushButton(self.configTab)
        self.resetViewButton.setObjectName("resetViewButton")
        self.gridLayout_2.addWidget(self.resetViewButton, 4, 0, 1, 2)
        self.verticalLayout_10.addLayout(self.gridLayout_2)
        self.mainTabWidget.addTab(self.configTab, "")
        self.verticalLayout_4.addWidget(self.mainTabWidget)
        self.mainDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.mainDock)
        self.infoDock = QtGui.QDockWidget(MainWindow)
        self.infoDock.setMaximumSize(QtCore.QSize(250, 524287))
        self.infoDock.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.infoDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.infoDock.setObjectName("infoDock")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.build_hardwareTabWidget = QtGui.QTabWidget(self.dockWidgetContents_2)
        self.build_hardwareTabWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.build_hardwareTabWidget.setFont(font)
        self.build_hardwareTabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.build_hardwareTabWidget.setObjectName("build_hardwareTabWidget")
        self.hardwareStatusTab = QtGui.QWidget()
        self.hardwareStatusTab.setObjectName("hardwareStatusTab")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.hardwareStatusTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.hardwareStatusTextBrowser = QtGui.QTextBrowser(self.hardwareStatusTab)
        self.hardwareStatusTextBrowser.setMinimumSize(QtCore.QSize(185, 0))
        self.hardwareStatusTextBrowser.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hardwareStatusTextBrowser.setObjectName("hardwareStatusTextBrowser")
        self.verticalLayout_9.addWidget(self.hardwareStatusTextBrowser)
        self.build_hardwareTabWidget.addTab(self.hardwareStatusTab, "")
        self.buildInfoTab = QtGui.QWidget()
        self.buildInfoTab.setObjectName("buildInfoTab")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.buildInfoTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.buildInfoTextBrowser = QtGui.QTextBrowser(self.buildInfoTab)
        self.buildInfoTextBrowser.setMinimumSize(QtCore.QSize(100, 0))
        self.buildInfoTextBrowser.setMaximumSize(QtCore.QSize(200, 16777215))
        self.buildInfoTextBrowser.setObjectName("buildInfoTextBrowser")
        self.verticalLayout_8.addWidget(self.buildInfoTextBrowser)
        self.build_hardwareTabWidget.addTab(self.buildInfoTab, "")
        self.verticalLayout_7.addWidget(self.build_hardwareTabWidget)
        self.infoDock.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.infoDock)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen_Recent = QtGui.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setShortcut("Ctrl+Q")
        self.actionQuit.setObjectName("actionQuit")
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon8)
        self.actionConnect.setShortcut("Ctrl+C")
        self.actionConnect.setObjectName("actionConnect")
        self.actionImport = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon9)
        self.actionImport.setShortcut("Ctrl+O")
        self.actionImport.setObjectName("actionImport")
        self.actionSlice = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/slice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSlice.setIcon(icon10)
        self.actionSlice.setShortcut("Ctrl+S")
        self.actionSlice.setObjectName("actionSlice")
        self.actionPrint = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon11)
        self.actionPrint.setShortcut("Ctrl+P")
        self.actionPrint.setObjectName("actionPrint")
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon12)
        self.actionPause.setShortcut("P")
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon13)
        self.actionStop.setShortcut("S")
        self.actionStop.setObjectName("actionStop")
        self.actionMain_tools = QtGui.QAction(MainWindow)
        self.actionMain_tools.setCheckable(True)
        self.actionMain_tools.setChecked(True)
        self.actionMain_tools.setObjectName("actionMain_tools")
        self.actionStatus_Info = QtGui.QAction(MainWindow)
        self.actionStatus_Info.setCheckable(True)
        self.actionStatus_Info.setChecked(True)
        self.actionStatus_Info.setObjectName("actionStatus_Info")
        self.actionToolbar = QtGui.QAction(MainWindow)
        self.actionToolbar.setCheckable(True)
        self.actionToolbar.setChecked(True)
        self.actionToolbar.setObjectName("actionToolbar")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionSpanish_Spain = QtGui.QAction(MainWindow)
        self.actionSpanish_Spain.setCheckable(True)
        self.actionSpanish_Spain.setObjectName("actionSpanish_Spain")
        self.actionCatalan = QtGui.QAction(MainWindow)
        self.actionCatalan.setCheckable(True)
        self.actionCatalan.setObjectName("actionCatalan")
        self.actionPortuguese_Brazil = QtGui.QAction(MainWindow)
        self.actionPortuguese_Brazil.setCheckable(True)
        self.actionPortuguese_Brazil.setObjectName("actionPortuguese_Brazil")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuShow_Tools.addAction(self.actionMain_tools)
        self.menuShow_Tools.addSeparator()
        self.menuShow_Tools.addAction(self.actionStatus_Info)
        self.menuShow_Tools.addSeparator()
        self.menuShow_Tools.addAction(self.actionToolbar)
        self.menuHelp.addAction(self.actionAbout)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionSpanish_Spain)
        self.menuLanguage.addAction(self.actionCatalan)
        self.menuLanguage.addAction(self.actionPortuguese_Brazil)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuShow_Tools.menuAction())
        self.menubar.addAction(self.menuLanguage.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImport)
        self.toolBar.addAction(self.actionSlice)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        self.build_hardwareTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuShow_Tools.setTitle(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLanguage.setTitle(QtGui.QApplication.translate("MainWindow", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.incrementLabel.setText(QtGui.QApplication.translate("MainWindow", "Incr.", None, QtGui.QApplication.UnicodeUTF8))
        self.positionLabel.setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLabel.setText(QtGui.QApplication.translate("MainWindow", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.syringe1Label.setText(QtGui.QApplication.translate("MainWindow", "Syringe 1 (Left):", None, QtGui.QApplication.UnicodeUTF8))
        self.syringe2Label.setText(QtGui.QApplication.translate("MainWindow", "Syringe 2 (Right):", None, QtGui.QApplication.UnicodeUTF8))
        self.autoCalibrateButton.setText(QtGui.QApplication.translate("MainWindow", "Auto Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.setHomeButton.setText(QtGui.QApplication.translate("MainWindow", "Set Home", None, QtGui.QApplication.UnicodeUTF8))
        self.setSafeButton.setText(QtGui.QApplication.translate("MainWindow", "Set Safe", None, QtGui.QApplication.UnicodeUTF8))
        self.setOriginButton.setText(QtGui.QApplication.translate("MainWindow", "Set Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.goHomeButton.setText(QtGui.QApplication.translate("MainWindow", "Go Home", None, QtGui.QApplication.UnicodeUTF8))
        self.goSafeButton.setText(QtGui.QApplication.translate("MainWindow", "Go Safe", None, QtGui.QApplication.UnicodeUTF8))
        self.goOriginButton.setText(QtGui.QApplication.translate("MainWindow", "Go Origin", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.moveTab), QtGui.QApplication.translate("MainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.importModelButton.setText(QtGui.QApplication.translate("MainWindow", "Import Model", None, QtGui.QApplication.UnicodeUTF8))
        self.modelTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Models", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.modelTab), QtGui.QApplication.translate("MainWindow", "Model/Path", None, QtGui.QApplication.UnicodeUTF8))
        self.portLabel.setText(QtGui.QApplication.translate("MainWindow", "Printer Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.configTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.configTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.configTreeWidget.isSortingEnabled()
        self.configTreeWidget.setSortingEnabled(False)
        self.configTreeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Printer", None, QtGui.QApplication.UnicodeUTF8))
        self.configTreeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Syringe 1", None, QtGui.QApplication.UnicodeUTF8))
        self.configTreeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Syringe 2", None, QtGui.QApplication.UnicodeUTF8))
        self.configTreeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Extruder", None, QtGui.QApplication.UnicodeUTF8))
        self.configTreeWidget.topLevelItem(4).setText(0, QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.configTreeWidget.setSortingEnabled(__sortingEnabled)
        self.printConfigLabel.setText(QtGui.QApplication.translate("MainWindow", "Printing:", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseAtToolChangeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Pause at Tool Change", None, QtGui.QApplication.UnicodeUTF8))
        self.autoResumeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Auto Resume", None, QtGui.QApplication.UnicodeUTF8))
        self.graphicsConfigLabel.setText(QtGui.QApplication.translate("MainWindow", "Graphics:", None, QtGui.QApplication.UnicodeUTF8))
        self.showModelCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Show Model", None, QtGui.QApplication.UnicodeUTF8))
        self.showPrinterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Show Printer", None, QtGui.QApplication.UnicodeUTF8))
        self.showPathsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Show Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.showTracesCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Show Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.renderWireframeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Render Wireframe", None, QtGui.QApplication.UnicodeUTF8))
        self.resetViewButton.setText(QtGui.QApplication.translate("MainWindow", "Reset View", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.infoDock.setAccessibleName(QtGui.QApplication.translate("MainWindow", "hardwareStatusDock", None, QtGui.QApplication.UnicodeUTF8))
        self.build_hardwareTabWidget.setTabText(self.build_hardwareTabWidget.indexOf(self.hardwareStatusTab), QtGui.QApplication.translate("MainWindow", "Hardware Status", None, QtGui.QApplication.UnicodeUTF8))
        self.build_hardwareTabWidget.setTabText(self.build_hardwareTabWidget.indexOf(self.buildInfoTab), QtGui.QApplication.translate("MainWindow", "Build Info", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Recent.setText(QtGui.QApplication.translate("MainWindow", "Open Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setToolTip(QtGui.QApplication.translate("MainWindow", "Connects to fab@home printer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setToolTip(QtGui.QApplication.translate("MainWindow", "Imports a model to print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSlice.setText(QtGui.QApplication.translate("MainWindow", "Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSlice.setToolTip(QtGui.QApplication.translate("MainWindow", "Slices the model and does the path planning", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setToolTip(QtGui.QApplication.translate("MainWindow", "Starts printing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setToolTip(QtGui.QApplication.translate("MainWindow", "Pauses/Resumes printing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setToolTip(QtGui.QApplication.translate("MainWindow", "Stops printing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMain_tools.setText(QtGui.QApplication.translate("MainWindow", "Main tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatus_Info.setText(QtGui.QApplication.translate("MainWindow", "Status/Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbar.setText(QtGui.QApplication.translate("MainWindow", "Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnglish.setText(QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpanish_Spain.setText(QtGui.QApplication.translate("MainWindow", "Spanish (Spain)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCatalan.setText(QtGui.QApplication.translate("MainWindow", "Catalan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPortuguese_Brazil.setText(QtGui.QApplication.translate("MainWindow", "Portuguese (Brazil)", None, QtGui.QApplication.UnicodeUTF8))

from vtk.qt4.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
import resources_rc
